const Problem=require("../models/Problem");
const Session=require("../models/Session");
const {generateHints,generateEdgeCases} = require("../services/aiService");

exports.createProblem=async(req,res)=>{

    console.log("CREATE PROBLEM API CALLED");

    console.log("BODY:",req.body);

    try{

        const old=await Problem.findOne({

            platform:req.body.platform,

            contestId:req.body.contestId,

            problemIndex:req.body.problemIndex

        });

        if(old){

    if(!old.aiGenerated){

        console.log("Generating missing AI for cached problem...");

        try{

            const [edgeCases,hints]=await Promise.all([

                generateEdgeCases(old),

                generateHints(

                    old.problemName,

                    old.statement,

                    old.constraints

                )

            ]);

            old.edgeCases=edgeCases.edgeCases;

            old.hints=hints.hints.map((x,i)=>({

                level:i+1,

                text:x

            }));

            old.aiGenerated=true;

            old.generatedAt=new Date();

            await old.save();

        }

        catch(e){

            console.error(e);

        }

    }

    console.log("Returning Cached Problem");

    return res.status(200).json({

        success:true,

        cached:true,

        data:old

    });

}

        const s=await Session.findOne({

            status:"ACTIVE"

        }).sort({

            createdAt:-1

        });

        if(s){

            s.totalDuration+=Math.floor(

                (new Date()-s.lastResumeTime)/1000

            );

            s.status="PAUSED";

            await s.save();

        }

        console.log("BEFORE CREATE");

        const p=await Problem.create(req.body);

        console.log("Generating AI Content...");

        const [edgeCases,hints]=await Promise.all([

            generateEdgeCases(p),

            generateHints(

                p.problemName,

                p.statement,

                p.constraints

            )

        ]);

        if(

            !edgeCases.edgeCases ||

            edgeCases.edgeCases.length!==3

        ){

            throw new Error(

                "Invalid edge cases generated by Gemini"

            );

        }

        if(

            !hints.hints ||

            hints.hints.length!==3

        ){

            throw new Error(

                "Invalid hints generated by Gemini"

            );

        }

        p.edgeCases=edgeCases.edgeCases;

        p.hints=hints.hints.map((x,i)=>({

        level:i+1,

         text:x

        }));

        p.aiGenerated=true;

        p.generatedAt=new Date();

        await p.save();

        console.log("Gemini Edge Cases:",edgeCases);

        console.log("Gemini Hints:",hints);

        console.log("AI Content Saved");

        console.log("AFTER CREATE");

        res.status(201).json({

            success:true,

            data:p

        });

    }

    catch(e){

        console.log("ERROR OCCURRED");

        console.error(e);

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};
exports.getProblems=async(req,res)=>{

    try{

        const a=await Problem.find().sort({

            createdAt:-1

        });

        res.status(200).json({

            success:true,

            count:a.length,

            data:a

        });

    }

    catch(e){

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};

exports.getProblemById=async(req,res)=>{

    try{

        const a=await Problem.findById(

            req.params.id

        );

        if(!a){

            return res.status(404).json({

                success:false,

                message:"Problem not found"

            });

        }

        res.status(200).json({

            success:true,

            data:a

        });

    }

    catch(e){

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};

exports.updateProblem=async(req,res)=>{

    try{

        const a=await Problem.findByIdAndUpdate(

            req.params.id,

            req.body,

            {

                new:true,

                runValidators:true

            }

        );

        if(!a){

            return res.status(404).json({

                success:false,

                message:"Problem not found"

            });

        }

        res.status(200).json({

            success:true,

            data:a

        });

    }

    catch(e){

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};

exports.deleteProblem=async(req,res)=>{

    try{

        const a=await Problem.findByIdAndDelete(

            req.params.id

        );

        if(!a){

            return res.status(404).json({

                success:false,

                message:"Problem not found"

            });

        }

        res.status(200).json({

            success:true,

            message:"Problem deleted"

        });

    }

    catch(e){

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};

exports.getLatestProblem=async(req,res)=>{

    try{

        const a=await Problem.findOne().sort({

            createdAt:-1

        });

        if(!a){

            return res.status(404).json({

                success:false,

                message:"No problem found"

            });

        }

        res.status(200).json({

            success:true,

            data:a

        });

    }

    catch(e){

        res.status(500).json({

            success:false,

            message:e.message

        });

    }

};